# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LandSat8_AtmosphericDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/大气校正.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.pushButton_input = QtWidgets.QPushButton(Dialog)
        self.pushButton_input.setGeometry(QtCore.QRect(10, 70, 91, 31))
        self.pushButton_input.setObjectName("pushButton_input")
        self.lineEdit_input = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_input.setGeometry(QtCore.QRect(110, 70, 281, 31))
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.pushButton_output = QtWidgets.QPushButton(Dialog)
        self.pushButton_output.setGeometry(QtCore.QRect(10, 170, 91, 31))
        self.pushButton_output.setObjectName("pushButton_output")
        self.lineEdit_output = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_output.setGeometry(QtCore.QRect(110, 170, 281, 31))
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.pushButton_ok = QtWidgets.QPushButton(Dialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(140, 250, 93, 28))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setGeometry(QtCore.QRect(290, 250, 93, 28))
        self.pushButton_cancel.setObjectName("pushButton_cancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "LandSat-8大气校正"))
        self.pushButton_input.setText(_translate("Dialog", "输入路径"))
        self.lineEdit_input.setText(_translate("Dialog", "E:\\AARS\\QGIS\\Data\\LC81240322020287LGN00"))
        self.pushButton_output.setText(_translate("Dialog", "输出路径"))
        self.pushButton_ok.setText(_translate("Dialog", "OK"))
        self.pushButton_cancel.setText(_translate("Dialog", "cancel"))
from resources import MyRc_rc
